[server]
enableStaticServing = true

[theme]
primaryColor = "#4bbcba"
backgroundColor = "#fafafa"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e1e1e"
font = "Sans-serif"

[[theme.fontFaces]]
family = "Baloo2"
url = "static/Baloo2-Regular.ttf"

[server]
enableCORS = false
headless = true
enableXsrfProtection = false