openai_apikey = "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"
assistant_id = "asst_KkZx8jxRGcc6TkYX3zTwx7hH"

smtp_user = "admin@movebuddy.eu"
smtp_pass = "abhe wokb iyxs dkia"
